function [control] = getControl(x, params)
    control = params.g / params.l * sin(x(1)) ...
              - params.k_phi * (x(1) - params.x_ref(1)) ...
              - params.k_omega * (x(2) - params.x_ref(2));
end